/**
 * Preview map auto-generated by scripts/generate-preview-index.mjs.
 * Regenerate after adding/removing components from registry.json.
 *
 *   node scripts/generate-preview-index.mjs
 */
import type { ComponentType, ReactNode } from "react"
import dynamic from "next/dynamic"
import type { PreviewLoader } from "@sntlr/registry-shell/shell/lib/registry-adapter"

const map: Record<string, ComponentType> = {
  "accordion": dynamic(() => import("./accordion-preview").then((m) => m.AccordionPreview)),
  "alert": dynamic(() => import("./alert-preview").then((m) => m.AlertPreview)),
  "alert-dialog": dynamic(() => import("./alert-dialog-preview").then((m) => m.AlertDialogPreview)),
  "aspect-ratio": dynamic(() => import("./aspect-ratio-preview").then((m) => m.AspectRatioPreview)),
  "avatar": dynamic(() => import("./avatar-preview").then((m) => m.AvatarPreview)),
  "badge": dynamic(() => import("./badge-preview").then((m) => m.BadgePreview)),
  "breadcrumb": dynamic(() => import("./breadcrumb-preview").then((m) => m.BreadcrumbPreview)),
  "button": dynamic(() => import("./button-preview").then((m) => m.ButtonPreview)),
  "calendar": dynamic(() => import("./calendar-preview").then((m) => m.CalendarPreview)),
  "card": dynamic(() => import("./card-preview").then((m) => m.CardPreview)),
  "carousel": dynamic(() => import("./carousel-preview").then((m) => m.CarouselPreview)),
  "chart": dynamic(() => import("./chart-preview").then((m) => m.ChartPreview)),
  "checkbox": dynamic(() => import("./checkbox-preview").then((m) => m.CheckboxPreview)),
  "collapsible": dynamic(() => import("./collapsible-preview").then((m) => m.CollapsiblePreview)),
  "command": dynamic(() => import("./command-preview").then((m) => m.CommandPreview)),
  "context-menu": dynamic(() => import("./context-menu-preview").then((m) => m.ContextMenuPreview)),
  "dialog": dynamic(() => import("./dialog-preview").then((m) => m.DialogPreview)),
  "drawer": dynamic(() => import("./drawer-preview").then((m) => m.DrawerPreview)),
  "dropdown-menu": dynamic(() => import("./dropdown-menu-preview").then((m) => m.DropdownMenuPreview)),
  "form": dynamic(() => import("./form-preview").then((m) => m.FormPreview)),
  "hover-card": dynamic(() => import("./hover-card-preview").then((m) => m.HoverCardPreview)),
  "input": dynamic(() => import("./input-preview").then((m) => m.InputPreview)),
  "input-otp": dynamic(() => import("./input-otp-preview").then((m) => m.InputOtpPreview)),
  "label": dynamic(() => import("./label-preview").then((m) => m.LabelPreview)),
  "menubar": dynamic(() => import("./menubar-preview").then((m) => m.MenubarPreview)),
  "navigation-menu": dynamic(() => import("./navigation-menu-preview").then((m) => m.NavigationMenuPreview)),
  "pagination": dynamic(() => import("./pagination-preview").then((m) => m.PaginationPreview)),
  "popover": dynamic(() => import("./popover-preview").then((m) => m.PopoverPreview)),
  "progress": dynamic(() => import("./progress-preview").then((m) => m.ProgressPreview)),
  "radio-group": dynamic(() => import("./radio-group-preview").then((m) => m.RadioGroupPreview)),
  "resizable": dynamic(() => import("./resizable-preview").then((m) => m.ResizablePreview)),
  "scroll-area": dynamic(() => import("./scroll-area-preview").then((m) => m.ScrollAreaPreview)),
  "select": dynamic(() => import("./select-preview").then((m) => m.SelectPreview)),
  "separator": dynamic(() => import("./separator-preview").then((m) => m.SeparatorPreview)),
  "sheet": dynamic(() => import("./sheet-preview").then((m) => m.SheetPreview)),
  "sidebar": dynamic(() => import("./sidebar-preview").then((m) => m.SidebarPreview)),
  "skeleton": dynamic(() => import("./skeleton-preview").then((m) => m.SkeletonPreview)),
  "slider": dynamic(() => import("./slider-preview").then((m) => m.SliderPreview)),
  "sonner": dynamic(() => import("./sonner-preview").then((m) => m.SonnerPreview)),
  "switch": dynamic(() => import("./switch-preview").then((m) => m.SwitchPreview)),
  "table": dynamic(() => import("./table-preview").then((m) => m.TablePreview)),
  "tabs": dynamic(() => import("./tabs-preview").then((m) => m.TabsPreview)),
  "textarea": dynamic(() => import("./textarea-preview").then((m) => m.TextareaPreview)),
  "toggle": dynamic(() => import("./toggle-preview").then((m) => m.TogglePreview)),
  "toggle-group": dynamic(() => import("./toggle-group-preview").then((m) => m.ToggleGroupPreview)),
  "tooltip": dynamic(() => import("./tooltip-preview").then((m) => m.TooltipPreview)),
  "wallet": dynamic(() => import("./wallet-preview").then((m) => m.WalletPreview)),
  "connect-wallet": dynamic(() => import("./connect-wallet-preview").then((m) => m.ConnectWalletPreview)),
  "token-amount": dynamic(() => import("./token-amount-preview").then((m) => m.TokenAmountPreview)),
  "network-badge": dynamic(() => import("./network-badge-preview").then((m) => m.NetworkBadgePreview)),
  "tx-status": dynamic(() => import("./tx-status-preview").then((m) => m.TxStatusPreview)),
  "nft-card": dynamic(() => import("./nft-card-preview").then((m) => m.NftCardPreview)),
  "swap-form": dynamic(() => import("./swap-form-preview").then((m) => m.SwapFormPreview)),
}

export const previewLoader: PreviewLoader = {
  Preview: ({ name, fallback }: { name: string; fallback?: ReactNode }) => {
    const Component = map[name]
    if (!Component) return fallback ?? null
    return <Component />
  },
  load: (name: string) => map[name] ?? null,
  names: () => Object.keys(map),
}
